### PR TITLE
Make `TryLock::new` `const fn`

### PR DESCRIPTION
**Pull request by yvt**
Enables the use of `TryLock::new` in a constant context.

Requires Rust 1.31.0 or later and discontinues the support for the older versions. (I'd like to hear your opinion on this - Do you still intend to support Rust 1.21? Or can we drop the support after a major version bump?)

### CODE REVIEW

**Comment by chrysn** [comment]
@seanmonstar, could you have a look at this? Apart from the constness, it looks like a TryLock would be very useful for static items.

**Comment by Chris--B** [comment]
Pinging here, because I ran into the exact issue and would love to use a crates.io version of this instead of a GitHub fork. Using this in `static` items effectively requires `TryLock::new` be `const`, and moving the MSRV up from very old to pretty old seems like an easy ask imo.

**Comment by Finomnis** [comment]
@seanmonstar Any thoughts on this? Two years later now, bumping the min version to `1.31` really doesn't seem like much of an issue any more :)
I'm also in favor of removing the deprecated function and releasing a 1.0 version, since this crate seems quite battle tested. (>90 Mil downloads on crates.io)

**Review by seanmonstar — APPROVED** [review]
1.21 to 1.31 is a pretty reasonable change at this point. It's still several years ago.

**Pull request merged**
